[project]
name = "stack-bruiser"
version = "0.1.0"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["utils", "constants", "preprocessing", "indexor", "data", "semantic_search", "retrieval_models", "back_end"]
